---
- name: Criando a instância EC2
  ec2:
    group: "{{ sec_group_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: true
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    count: "{{ count }}"
  register: ec2

- name: Adicionando uma tag na instância
  ec2_tag:
    resource: "{{ item.id }}"
    region: "{{ region }}"
    state: present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: "ansible-{{ item.ami_launch_index |int + 1}}"

- name: Adicionando a instância ao inventário temporário
  add_host:
    name: "{{ item.public_ip }}"
    groups: "kubernetes_new"
  with_items: "{{ ec2.instances }}"

- name: Adicionando o IP público da instância criada ao arquivo hosts
  lineinfile:
    dest: "./hosts"
    regexp: "{{ item.public_ip }}"
    insertafter: "[kubernetes]"
    line: "{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"

- name: Adicionando o IP privado da instância criada ao arquivo hosts
  lineinfile:
    dest: "./hosts"
    regexp: "{{ item.private_ip }}"
    insertafter: "[kubernetes]"
    line: "{{ item.private_ip }}"
  with_items: "{{ ec2.instances }}"

- name: Esperando subir o SSH
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"
...