- name: Verificando se o Docker já existe
  shell: docker info
  ignore_errors: true
  register: docker_info

- name: Instalando o docker
  shell: "curl -fsSL https://get.docker.com | bash"
  when: docker_info.rc != 0

- name: Copiando arquivo para setar cgroups driver como systemd
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  when: docker_info.rc != 0
  notify: Restart Docker

- name: Adicionando as chaves do repo APT do K8S
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Adicionando o repo do K8S
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Instalando os pacotes kubeadm, kubelet e kubectl
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  notify: Restart Kubelet