- name: Adicionando o repositório no HELM
  shell: "helm repo add {{ prometheus_repo_url }}"
  register: prometheus_add_repo

- name: Atualizando os repositórios do HELM
  shell: "helm repo update"
  register: prometheus_update_repo

- name: Instalando o prometheus operator
  shell: "helm install {{ deploy_prometheus }}"
  register: prometheus_install