- name: Criando o diretório da app Giropops
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ app_folders }}"

- name: Copiando o arquivo de deployment da app para o host
  template:
    src: app-v1.yml.j2
    dest: "{{ deploy_file }}"
    owner: root
    group: root
    mode: 0655
  register: template_copy

- name: Copiando o arquivo de service da app para o host
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ service_files }}"
  register: service_copy

- name: Executando o deployment da App giropops
  shell: "kubectl apply -f {{ deploy_file }}"
  register: deploy_app

- name: Criando o serviço da aplicação
  shell: "kubectl apply -f {{ item.dest }}"
  with_items: "{{ service_files }}"
  register: deploy_svc_app