- name: Verificando se jรก temos o helm
  shell: "helm version"
  ignore_errors: true
  register: helm_version

- name: Baixando o HELM
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp/get_helm.sh
    mode: 0755
  register: download
  when: helm_version.rc != 0

- name: Instalando o HELM
  shell: /tmp/get_helm.sh
  when: download.failed | bool == false
  register: install_helm
  when: helm_version.rc != 0